# Generated by Django 5.2.11 on 2026-02-12 23:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('firms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MappingTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('is_default', models.BooleanField(default=False, help_text="If true, this is the firm's default template (client must be null).")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, help_text='If set, this template overrides the firm default for this client.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mapping_templates', to='clients.client')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapping_templates', to='firms.firm')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MappingRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('match_mode', models.CharField(choices=[('exact', 'Exact match on account number'), ('prefix', 'Account number starts with'), ('contains', 'Account name contains')], default='exact', max_length=20)),
                ('match_value', models.CharField(help_text='The value to match against (account number or name fragment).', max_length=255)),
                ('target_line', models.CharField(help_text="Tax form line identifier, e.g. '1120S_L1a' or 'Line 1a'.", max_length=100)),
                ('target_description', models.CharField(blank=True, default='', help_text="Human-readable label, e.g. 'Gross receipts or sales'.", max_length=255)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority rules match first when multiple rules match.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='mappings.mappingtemplate')),
            ],
            options={
                'ordering': ['-priority', 'match_value'],
            },
        ),
        migrations.AddConstraint(
            model_name='mappingtemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('client__isnull', True), ('is_default', True)), fields=('firm',), name='one_default_per_firm'),
        ),
    ]
