# Generated by Django 5.2.11 on 2026-02-14 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='entity_type',
            field=models.CharField(choices=[('scorp', 'S-Corp (1120S)'), ('partnership', 'Partnership (1065)'), ('ccorp', 'C-Corp (1120)'), ('trust', 'Trust (1041)'), ('individual', 'Individual (1040)')], default='scorp', max_length=20),
        ),
    ]
