# Generated by Django 5.2.11 on 2026-02-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_add_all_entity_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='address_line1',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='entity',
            name='address_line2',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='entity',
            name='business_activity',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='entity',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='entity',
            name='date_incorporated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='ein',
            field=models.CharField(blank=True, default='', help_text='EIN in XX-XXXXXXX format', max_length=20),
        ),
        migrations.AddField(
            model_name='entity',
            name='legal_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='entity',
            name='naics_code',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='entity',
            name='state',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AddField(
            model_name='entity',
            name='state_incorporated',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AddField(
            model_name='entity',
            name='zip_code',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
