# Generated by Django 5.2.11 on 2026-02-20 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0003_entity_profile_fields"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="entity",
            constraint=models.UniqueConstraint(
                fields=("client", "name", "entity_type"),
                name="unique_client_entity_name_type",
            ),
        ),
    ]
