# Generated by Django 5.2.11 on 2026-02-20 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0004_entity_unique_client_name_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="phone",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Business phone number.",
                max_length=20,
            ),
        ),
    ]
