# Generated by Django 5.2.11 on 2026-02-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0005_phase2_header_flags_preparer"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="entity",
            name="spouse_first_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="entity",
            name="spouse_last_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="entity",
            name="spouse_ssn",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Spouse SSN in XXX-XX-XXXX format",
                max_length=20,
            ),
        ),
    ]
