# Generated by Django 5.2.11 on 2026-02-25 00:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0006_add_spouse_and_email_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientEntityLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("taxpayer", "Taxpayer"),
                            ("shareholder", "Shareholder"),
                            ("partner", "Partner"),
                            ("officer", "Officer"),
                        ],
                        default="taxpayer",
                        max_length=20,
                    ),
                ),
                (
                    "ownership_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Ownership percentage (e.g. 60.0000 for 60%)",
                        max_digits=7,
                        null=True,
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Primary owner/taxpayer for this entity.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entity_links",
                        to="clients.client",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_links",
                        to="clients.entity",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_primary", "client__name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("client", "entity", "role"),
                        name="unique_client_entity_role",
                    )
                ],
            },
        ),
    ]
