# Generated by Django 5.2.11 on 2026-03-01 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0007_cliententitylink"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxyear",
            name="filing_states",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of 2-letter state codes this entity files in, e.g. ['GA', 'AL']",
            ),
        ),
    ]
