# Generated by Django 5.2.11 on 2026-05-07 18:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "ein",
                    models.CharField(
                        db_index=True,
                        help_text="Federal EIN, format XX-XXXXXXX",
                        max_length=10,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("street", models.CharField(blank=True, default="", max_length=255)),
                ("city", models.CharField(blank=True, default="", max_length=100)),
                ("state", models.CharField(blank=True, default="", max_length=2)),
                (
                    "zip",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="5-digit or ZIP+4 format",
                        max_length=10,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("taxwise_import", "TaxWise bulk import"),
                            ("user_entered", "User entered during W-2 entry"),
                        ],
                        default="user_entered",
                        max_length=20,
                    ),
                ),
                (
                    "verified",
                    models.BooleanField(
                        default=False,
                        help_text="Preparer confirmed employer details are correct",
                    ),
                ),
                (
                    "parse_warning",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Populated for rows that needed cleanup during import",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="EmployerStateAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("state", models.CharField(max_length=2)),
                (
                    "state_id_number",
                    models.CharField(
                        help_text="State-issued withholding account number",
                        max_length=30,
                    ),
                ),
                ("source", models.CharField(default="user_entered", max_length=20)),
                ("verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="state_accounts",
                        to="employers.employer",
                    ),
                ),
            ],
            options={
                "ordering": ["state"],
                "unique_together": {("employer", "state")},
            },
        ),
        # Enable Row Level Security on the new tables to match the April 21
        # Cowork audit policy (apps.core.migrations.0001). Default-deny: no
        # policies are created. Django connects as Postgres superuser via
        # the pooler and bypasses RLS, so ORM queries are unaffected. The
        # protection applies to connections via PostgREST / supabase-js /
        # the anon key, which should see zero rows.
        migrations.RunSQL(
            sql="ALTER TABLE employers_employer ENABLE ROW LEVEL SECURITY;",
            reverse_sql="ALTER TABLE employers_employer DISABLE ROW LEVEL SECURITY;",
        ),
        migrations.RunSQL(
            sql="ALTER TABLE employers_employerstateaccount ENABLE ROW LEVEL SECURITY;",
            reverse_sql="ALTER TABLE employers_employerstateaccount DISABLE ROW LEVEL SECURITY;",
        ),
    ]
