# Generated by Django 5.2.11 on 2026-04-02 23:57

import apps.documents.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0008_taxyear_filing_states"),
        ("firms", "0003_add_print_package"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.documents.models.document_upload_path
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("file_size", models.BigIntegerField(default=0)),
                (
                    "content_type",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("w2", "W-2"),
                            ("1099", "1099"),
                            ("receipt", "Receipt"),
                            ("bank_statement", "Bank Statement"),
                            ("k1", "K-1"),
                            ("engagement_letter", "Engagement Letter"),
                            ("tax_return", "Completed Tax Return"),
                            ("extension", "Extension (7004)"),
                            ("organizer", "Tax Organizer"),
                            ("correspondence", "IRS/State Correspondence"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                ("tax_year", models.IntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="clients.client",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="clients.entity",
                    ),
                ),
                (
                    "firm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="firms.firm",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["entity", "-created_at"],
                        name="documents_c_entity__92493a_idx",
                    ),
                    models.Index(
                        fields=["firm", "-created_at"],
                        name="documents_c_firm_id_b98c6b_idx",
                    ),
                    models.Index(
                        fields=["category"], name="documents_c_categor_7fa47c_idx"
                    ),
                ],
            },
        ),
    ]
