# Generated by Django 5.2.11 on 2026-02-21 15:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Preparer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "ptin",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Preparer Tax Identification Number.",
                        max_length=20,
                    ),
                ),
                ("is_self_employed", models.BooleanField(default=False)),
                ("firm_name", models.CharField(blank=True, default="", max_length=255)),
                ("firm_ein", models.CharField(blank=True, default="", max_length=20)),
                ("firm_phone", models.CharField(blank=True, default="", max_length=20)),
                (
                    "firm_address",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("firm_city", models.CharField(blank=True, default="", max_length=100)),
                ("firm_state", models.CharField(blank=True, default="", max_length=2)),
                ("firm_zip", models.CharField(blank=True, default="", max_length=10)),
                (
                    "designee_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "designee_phone",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "designee_pin",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "firm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preparers",
                        to="firms.firm",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
