# Generated by Django 5.2.11 on 2026-02-13 01:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('tax_year_applicable', models.IntegerField(help_text='The IRS tax year this definition covers.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='FormSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('sort_order', models.IntegerField(default=0)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='returns.formdefinition')),
            ],
            options={
                'ordering': ['sort_order'],
                'unique_together': {('form', 'code')},
            },
        ),
        migrations.CreateModel(
            name='FormLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_number', models.CharField(max_length=20)),
                ('label', models.CharField(max_length=300)),
                ('field_type', models.CharField(choices=[('currency', 'Currency'), ('integer', 'Integer'), ('text', 'Text'), ('boolean', 'Yes/No'), ('percentage', 'Percentage')], default='currency', max_length=20)),
                ('mapping_key', models.CharField(blank=True, default='', help_text="Key that bridges MappingRule.target_line → this form line. E.g. '1120S_L1a'. Leave blank for lines that are always manual.", max_length=60)),
                ('is_computed', models.BooleanField(default=False, help_text='True if this line is auto-calculated from other lines.')),
                ('sort_order', models.IntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='returns.formsection')),
            ],
            options={
                'ordering': ['sort_order'],
                'unique_together': {('section', 'line_number')},
            },
        ),
        migrations.CreateModel(
            name='TaxReturn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('in_review', 'In Review'), ('approved', 'Approved'), ('filed', 'Filed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_returns', to=settings.AUTH_USER_MODEL)),
                ('form_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='returns.formdefinition')),
                ('tax_year', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tax_return', to='clients.taxyear')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormFieldValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.TextField(blank=True, default='', help_text='Stored as text; interpreted per form_line.field_type.')),
                ('is_overridden', models.BooleanField(default=False, help_text='True if a user manually overrode the mapped/computed value.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('form_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='values', to='returns.formline')),
                ('tax_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='returns.taxreturn')),
            ],
            options={
                'ordering': ['form_line__sort_order'],
                'unique_together': {('tax_return', 'form_line')},
            },
        ),
    ]
