# Generated by Django 5.2.11 on 2026-02-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formline',
            name='normal_balance',
            field=models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], default='debit', help_text='Debit for expenses/assets; Credit for revenue/liabilities/equity. Controls sign when importing from trial balance.', max_length=6),
        ),
    ]
