# Generated by Django 5.2.11 on 2026-02-14 16:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0002_formline_normal_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxreturn',
            name='accounting_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('accrual', 'Accrual'), ('other', 'Other')], default='cash', max_length=10),
        ),
        migrations.AddField(
            model_name='taxreturn',
            name='tax_year_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxreturn',
            name='tax_year_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('ssn', models.CharField(blank=True, default='', max_length=11)),
                ('percent_ownership', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('compensation', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('sort_order', models.IntegerField(default=0)),
                ('tax_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officers', to='returns.taxreturn')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OtherDeduction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('sort_order', models.IntegerField(default=0)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('tb_import', 'TB Import')], default='manual', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tax_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_deductions', to='returns.taxreturn')),
            ],
            options={
                'ordering': ['sort_order', 'description'],
            },
        ),
    ]
