# Generated by Django 5.2.11 on 2026-02-16 21:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0003_otherdeduction_officer_return_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shareholder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('ssn', models.CharField(blank=True, default='', help_text='SSN or TIN (formatted XXX-XX-XXXX)', max_length=11)),
                ('address_line1', models.CharField(blank=True, default='', max_length=255)),
                ('address_line2', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=2)),
                ('zip_code', models.CharField(blank=True, default='', max_length=10)),
                ('ownership_percentage', models.DecimalField(decimal_places=4, default=0, help_text='Percentage of stock ownership for the tax year.', max_digits=7)),
                ('beginning_shares', models.IntegerField(default=0, help_text='Number of shares owned at beginning of tax year.')),
                ('ending_shares', models.IntegerField(default=0, help_text='Number of shares owned at end of tax year.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the shareholder was active during the tax year.')),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tax_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shareholders', to='returns.taxreturn')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
