# Generated by Django 5.2.11 on 2026-02-16 21:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0004_shareholder_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalProperty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(help_text='Property address or description.', max_length=255)),
                ('property_type', models.CharField(choices=[('1', 'Single family residence'), ('2', 'Multi-family residence'), ('3', 'Vacation/short-term rental'), ('4', 'Commercial'), ('5', 'Land'), ('6', 'Other')], default='6', max_length=1)),
                ('fair_rental_days', models.IntegerField(default=365)),
                ('personal_use_days', models.IntegerField(default=0)),
                ('rents_received', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('advertising', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('auto_and_travel', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cleaning_and_maintenance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('commissions', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('insurance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('legal_and_professional', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('interest_mortgage', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('interest_other', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('repairs', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('taxes', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('utilities', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('depreciation', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('other_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tax_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_properties', to='returns.taxreturn')),
            ],
            options={
                'ordering': ['sort_order', 'description'],
            },
        ),
    ]
