# Generated by Django 5.2.11 on 2026-02-16 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_entity_profile_fields'),
        ('returns', '0005_rental_property_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareholder',
            name='distributions',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cash and property distributions to this shareholder (K-1 line 16d).', max_digits=15),
        ),
        migrations.AddField(
            model_name='shareholder',
            name='health_insurance_premium',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Health insurance premiums paid by S-Corp for >2%% shareholder. Drives Form 7206.', max_digits=15),
        ),
        migrations.AddField(
            model_name='shareholder',
            name='linked_client',
            field=models.ForeignKey(blank=True, help_text='Link to a client record if this shareholder is also a client.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shareholder_links', to='clients.client'),
        ),
    ]
