# Generated by Django 5.2.11 on 2026-02-20 20:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("returns", "0006_shareholder_enhancements"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxreturn",
            name="business_activity_code",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Business activity code (IRS line I).",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="taxreturn",
            name="is_address_change",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="taxreturn",
            name="is_amended_return",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="taxreturn",
            name="is_final_return",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="taxreturn",
            name="is_initial_return",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="taxreturn",
            name="is_name_change",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="taxreturn",
            name="number_of_shareholders",
            field=models.IntegerField(
                blank=True,
                help_text="Number of shareholders during any part of the tax year.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="taxreturn",
            name="product_or_service",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Principal product or service (IRS line F).",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="taxreturn",
            name="s_election_date",
            field=models.DateField(
                blank=True, help_text="Date S-Corp election was effective.", null=True
            ),
        ),
        migrations.CreateModel(
            name="PreparerInfo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "preparer_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "ptin",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Preparer Tax Identification Number.",
                        max_length=20,
                    ),
                ),
                ("signature_date", models.DateField(blank=True, null=True)),
                ("is_self_employed", models.BooleanField(default=False)),
                ("firm_name", models.CharField(blank=True, default="", max_length=255)),
                ("firm_ein", models.CharField(blank=True, default="", max_length=20)),
                ("firm_phone", models.CharField(blank=True, default="", max_length=20)),
                (
                    "firm_address",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("firm_city", models.CharField(blank=True, default="", max_length=100)),
                ("firm_state", models.CharField(blank=True, default="", max_length=2)),
                ("firm_zip", models.CharField(blank=True, default="", max_length=10)),
                (
                    "designee_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "designee_phone",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "designee_pin",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tax_return",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preparer_info",
                        to="returns.taxreturn",
                    ),
                ),
            ],
        ),
    ]
