# Generated by Django 5.2.11 on 2026-02-21 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("returns", "0007_phase2_header_flags_preparer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rentalproperty",
            name="description",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Property address or description.",
                max_length=255,
            ),
        ),
    ]
