# Generated by Django 5.2.11 on 2026-02-21 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firms", "0002_preparer_model"),
        ("returns", "0008_fix_rental_description_blank"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxreturn",
            name="preparer",
            field=models.ForeignKey(
                blank=True,
                help_text="Assigned preparer from the firm's preparer list.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tax_returns",
                to="firms.preparer",
            ),
        ),
        migrations.AddField(
            model_name="taxreturn",
            name="signature_date",
            field=models.DateField(
                blank=True, help_text="Date the preparer signed the return.", null=True
            ),
        ),
    ]
