# Generated by Django 5.2.11 on 2026-02-21 15:12

from django.db import migrations


def migrate_preparer_info_to_preparers(apps, schema_editor):
    """Copy distinct PreparerInfo records into firm-level Preparer model.

    For each unique (preparer_name, ptin, firm), create one Preparer record
    and link the TaxReturn to it.
    """
    PreparerInfo = apps.get_model("returns", "PreparerInfo")
    Preparer = apps.get_model("firms", "Preparer")
    TaxReturn = apps.get_model("returns", "TaxReturn")

    # Build a cache: (firm_id, preparer_name, ptin) -> Preparer
    cache = {}

    for info in PreparerInfo.objects.select_related(
        "tax_return__tax_year__entity__client"
    ).all():
        tr = info.tax_return
        if not info.preparer_name:
            continue  # skip blank preparer records

        firm_id = tr.tax_year.entity.client.firm_id
        key = (firm_id, info.preparer_name, info.ptin)

        if key not in cache:
            preparer = Preparer.objects.create(
                firm_id=firm_id,
                name=info.preparer_name,
                ptin=info.ptin,
                is_self_employed=info.is_self_employed,
                firm_name=info.firm_name,
                firm_ein=info.firm_ein,
                firm_phone=info.firm_phone,
                firm_address=info.firm_address,
                firm_city=info.firm_city,
                firm_state=info.firm_state,
                firm_zip=info.firm_zip,
                designee_name=info.designee_name,
                designee_phone=info.designee_phone,
                designee_pin=info.designee_pin,
            )
            cache[key] = preparer

        # Link the return to the firm-level preparer
        tr.preparer = cache[key]
        tr.signature_date = info.signature_date
        tr.save(update_fields=["preparer", "signature_date"])


def reverse_noop(apps, schema_editor):
    """No reverse — the PreparerInfo records are still intact."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("returns", "0009_taxreturn_preparer_fk"),
        ("firms", "0002_preparer_model"),
    ]

    operations = [
        migrations.RunPython(
            migrate_preparer_info_to_preparers,
            reverse_noop,
        ),
    ]
