# Generated by Django 5.2.11 on 2026-02-27 16:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("returns", "0010_migrate_preparer_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="shareholder",
            name="capital_contributions",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Line 2: Stock purchases and capital contributions during year.",
                max_digits=15,
            ),
        ),
        migrations.AddField(
            model_name="shareholder",
            name="depletion",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Line 10: Depletion (entered by preparer).",
                max_digits=15,
            ),
        ),
        migrations.AddField(
            model_name="shareholder",
            name="stock_basis_boy",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Line 1: Stock basis at beginning of tax year.",
                max_digits=15,
            ),
        ),
        migrations.AddField(
            model_name="shareholder",
            name="suspended_1231_loss",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Prior year suspended net section 1231 loss.",
                max_digits=15,
            ),
        ),
        migrations.AddField(
            model_name="shareholder",
            name="suspended_lt_capital_loss",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Prior year suspended net long-term capital loss.",
                max_digits=15,
            ),
        ),
        migrations.AddField(
            model_name="shareholder",
            name="suspended_ordinary_loss",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Prior year suspended ordinary business loss.",
                max_digits=15,
            ),
        ),
        migrations.AddField(
            model_name="shareholder",
            name="suspended_other_loss",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Prior year suspended other loss/deduction items.",
                max_digits=15,
            ),
        ),
        migrations.AddField(
            model_name="shareholder",
            name="suspended_other_rental_loss",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Prior year suspended other net rental loss.",
                max_digits=15,
            ),
        ),
        migrations.AddField(
            model_name="shareholder",
            name="suspended_rental_re_loss",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Prior year suspended net rental real estate loss.",
                max_digits=15,
            ),
        ),
        migrations.AddField(
            model_name="shareholder",
            name="suspended_st_capital_loss",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Prior year suspended net short-term capital loss.",
                max_digits=15,
            ),
        ),
        migrations.CreateModel(
            name="ShareholderLoan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Description of the loan (e.g., 'Operating line of credit').",
                        max_length=255,
                    ),
                ),
                (
                    "loan_balance_boy",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Line 16: Beginning of year loan balance.",
                        max_digits=15,
                    ),
                ),
                (
                    "additional_loans",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Line 17: Additional loans made during year.",
                        max_digits=15,
                    ),
                ),
                (
                    "loan_repayments",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Line 19: Loan repayments during year.",
                        max_digits=15,
                    ),
                ),
                (
                    "debt_basis_boy",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Line 21: Debt basis at beginning of year.",
                        max_digits=15,
                    ),
                ),
                (
                    "new_loans_increasing_basis",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Line 22: Portion of new loans that increase debt basis.",
                        max_digits=15,
                    ),
                ),
                ("sort_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "shareholder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loans",
                        to="returns.shareholder",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "description"],
            },
        ),
    ]
