# Generated by Django 5.2.11 on 2026-02-27 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("returns", "0011_add_form_7203_basis_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxreturn",
            name="balance_due",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Form 7004 Line 8: Balance due (Line 6 minus Line 7).",
                max_digits=15,
            ),
        ),
        migrations.AddField(
            model_name="taxreturn",
            name="extension_date",
            field=models.DateField(
                blank=True,
                help_text="Date the Form 7004 extension was filed.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="taxreturn",
            name="extension_filed",
            field=models.BooleanField(
                default=False,
                help_text="Whether Form 7004 extension was filed for this return.",
            ),
        ),
        migrations.AddField(
            model_name="taxreturn",
            name="tentative_tax",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Form 7004 Line 6: Tentative total tax.",
                max_digits=15,
            ),
        ),
        migrations.AddField(
            model_name="taxreturn",
            name="total_payments",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Form 7004 Line 7: Total payments and credits.",
                max_digits=15,
            ),
        ),
    ]
