# Generated by Django 5.2.11 on 2026-02-27 23:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0007_cliententitylink"),
        ("returns", "0012_add_extension_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriorYearReturn",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("year", models.IntegerField(help_text="Tax year (e.g., 2024).")),
                (
                    "form_code",
                    models.CharField(
                        help_text="IRS form code (e.g., '1120-S').", max_length=20
                    ),
                ),
                (
                    "line_values",
                    models.JSONField(
                        default=dict,
                        help_text="Form line number → amount (e.g., {'1c': 112450, '22': 14938}).",
                    ),
                ),
                (
                    "other_deductions",
                    models.JSONField(
                        default=dict,
                        help_text="Other deduction detail: description → amount.",
                    ),
                ),
                (
                    "balance_sheet",
                    models.JSONField(
                        default=dict,
                        help_text="Balance sheet: 'L{line}_{boy|eoy}' → amount.",
                    ),
                ),
                (
                    "source_software",
                    models.CharField(
                        default="lacerte",
                        help_text="Software the data was imported from.",
                        max_length=50,
                    ),
                ),
                (
                    "source_file",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Original filename (for audit trail).",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prior_year_returns",
                        to="clients.entity",
                    ),
                ),
            ],
            options={
                "ordering": ["-year"],
                "unique_together": {("entity", "year", "form_code")},
            },
        ),
    ]
