# Generated by Django 5.2.11 on 2026-02-28 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("returns", "0013_add_prior_year_return"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otherdeduction",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("tb_import", "TB Import"),
                    ("standard", "Standard"),
                ],
                default="manual",
                max_length=10,
            ),
        ),
    ]
