# Generated by Django 5.2.11 on 2026-02-28 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("returns", "0014_alter_otherdeduction_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formline",
            name="label",
            field=models.CharField(max_length=500),
        ),
    ]
