# Generated by Django 5.2.11 on 2026-02-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("returns", "0015_increase_formline_label_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="prioryearreturn",
            name="m2_balances",
            field=models.JSONField(
                default=dict, help_text="Schedule M-2 balances: 'M2_{line}' → amount."
            ),
        ),
        migrations.AddField(
            model_name="prioryearreturn",
            name="officers",
            field=models.JSONField(
                default=list, help_text="Officers from Form 1125-E (list of dicts)."
            ),
        ),
        migrations.AddField(
            model_name="prioryearreturn",
            name="shareholders",
            field=models.JSONField(
                default=list, help_text="Shareholders from K-1 pages (list of dicts)."
            ),
        ),
    ]
