# Generated by Django 5.2.11 on 2026-02-28 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("returns", "0016_add_py_shareholders_officers_m2"),
    ]

    operations = [
        migrations.AddField(
            model_name="officer",
            name="percent_time",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Percent of time devoted to business.",
                max_digits=5,
            ),
        ),
    ]
