# Generated by Django 5.2.11 on 2026-02-28 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("returns", "0017_add_officer_percent_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxreturn",
            name="bank_account_number",
            field=models.CharField(
                blank=True, default="", help_text="Bank account number.", max_length=17
            ),
        ),
        migrations.AddField(
            model_name="taxreturn",
            name="bank_account_type",
            field=models.CharField(
                blank=True,
                choices=[("checking", "Checking"), ("savings", "Savings")],
                default="checking",
                help_text="Checking or Savings.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="taxreturn",
            name="bank_routing_number",
            field=models.CharField(
                blank=True,
                default="",
                help_text="9-digit ABA routing number.",
                max_length=9,
            ),
        ),
    ]
