# Generated by Django 5.2.11 on 2026-02-28 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firms", "0002_preparer_model"),
        ("returns", "0018_add_bank_info"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxreturn",
            name="staff_preparer",
            field=models.ForeignKey(
                blank=True,
                help_text="Staff preparer who entered the data (not the signer).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff_returns",
                to="firms.preparer",
            ),
        ),
    ]
