# Generated by Django 5.2.11 on 2026-03-01 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0007_cliententitylink"),
        ("returns", "0019_add_staff_preparer"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxreturn",
            name="federal_return",
            field=models.ForeignKey(
                blank=True,
                help_text="Links a state return to its federal return.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="state_returns",
                to="returns.taxreturn",
            ),
        ),
        migrations.AlterField(
            model_name="taxreturn",
            name="tax_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tax_returns",
                to="clients.taxyear",
            ),
        ),
    ]
