# Generated by Django 5.2.11 on 2026-03-06 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("returns", "0020_allow_multiple_returns_per_taxyear"),
    ]

    operations = [
        migrations.AddField(
            model_name="shareholderloan",
            name="interest_rate",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                help_text="Annual interest rate (e.g. 5.24 for 5.24%).",
                max_digits=6,
            ),
        ),
        migrations.AddField(
            model_name="shareholderloan",
            name="maturity_date",
            field=models.DateField(
                blank=True, help_text="Loan maturity date.", null=True
            ),
        ),
        migrations.AddField(
            model_name="shareholderloan",
            name="original_loan_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Original principal amount of the loan.",
                max_digits=15,
            ),
        ),
        migrations.AddField(
            model_name="shareholderloan",
            name="payment_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Regular payment amount.",
                max_digits=15,
            ),
        ),
    ]
