# Generated by Django 5.2.11 on 2026-03-06 14:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("returns", "0021_add_loan_detail_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="LineItemDetail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "line_number",
                    models.CharField(
                        help_text="Parent form line (e.g., 'M1_2', 'L6').",
                        max_length=20,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Amount (for single-column lines like M-1).",
                        max_digits=15,
                    ),
                ),
                (
                    "amount_boy",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Beginning of year amount (for Schedule L lines).",
                        max_digits=15,
                    ),
                ),
                (
                    "amount_eoy",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="End of year amount (for Schedule L lines).",
                        max_digits=15,
                    ),
                ),
                ("sort_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tax_return",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_item_details",
                        to="returns.taxreturn",
                    ),
                ),
            ],
            options={
                "ordering": ["line_number", "sort_order", "description"],
            },
        ),
    ]
