# Generated by Django 5.2.11 on 2026-03-08 19:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("returns", "0022_add_line_item_detail"),
    ]

    operations = [
        migrations.CreateModel(
            name="Disposition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Description of property sold or exchanged.",
                        max_length=255,
                    ),
                ),
                (
                    "date_acquired",
                    models.DateField(
                        blank=True,
                        help_text="Date property was acquired (null if various).",
                        null=True,
                    ),
                ),
                (
                    "date_acquired_various",
                    models.BooleanField(
                        default=False, help_text="True if acquired on various dates."
                    ),
                ),
                (
                    "date_sold",
                    models.DateField(
                        blank=True,
                        help_text="Date property was sold (null if various).",
                        null=True,
                    ),
                ),
                (
                    "date_sold_various",
                    models.BooleanField(
                        default=False, help_text="True if sold on various dates."
                    ),
                ),
                (
                    "sales_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Gross sales price.",
                        max_digits=15,
                    ),
                ),
                (
                    "cost_basis",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Cost or other basis (do not reduce by depreciation).",
                        max_digits=15,
                    ),
                ),
                (
                    "amt_cost_basis",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="AMT cost or other basis. Null = same as regular.",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "state_cost_basis",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="State cost or other basis. Null = same as regular.",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "state_amt_cost_basis",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="State AMT cost or other basis.",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "expenses_of_sale",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Expenses of sale or exchange.",
                        max_digits=15,
                    ),
                ),
                (
                    "term",
                    models.CharField(
                        choices=[("short", "Short-term"), ("long", "Long-term")],
                        default="long",
                        help_text="Short-term or long-term.",
                        max_length=5,
                    ),
                ),
                (
                    "nontaxable_federal",
                    models.BooleanField(
                        default=False, help_text="Nontaxable to federal."
                    ),
                ),
                (
                    "nontaxable_state",
                    models.BooleanField(
                        default=False, help_text="Nontaxable to state."
                    ),
                ),
                (
                    "related_party_loss",
                    models.BooleanField(default=False, help_text="Related party loss."),
                ),
                (
                    "securities_trader",
                    models.BooleanField(
                        default=False, help_text="Securities trader transaction."
                    ),
                ),
                (
                    "is_4797",
                    models.BooleanField(
                        default=False,
                        help_text="True = Form 4797 (investment property). False = Schedule D (noninvestment).",
                    ),
                ),
                (
                    "inherited_property",
                    models.BooleanField(
                        default=False,
                        help_text="Inherited property with stepped-up basis.",
                    ),
                ),
                (
                    "net_investment_income_tax",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No")],
                        default="yes",
                        help_text="Subject to net investment income tax.",
                        max_length=3,
                    ),
                ),
                ("sort_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tax_return",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispositions",
                        to="returns.taxreturn",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "description"],
            },
        ),
    ]
