# Generated by Django 5.2.11 on 2026-03-10 15:38

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("returns", "0023_add_disposition_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="DepreciationAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "asset_number",
                    models.IntegerField(
                        help_text="Auto-assigned per return, display only."
                    ),
                ),
                ("description", models.CharField(max_length=200)),
                (
                    "group_label",
                    models.CharField(
                        choices=[
                            ("Buildings", "Buildings"),
                            ("Machinery and Equipment", "Machinery and Equipment"),
                            ("Furniture and Fixtures", "Furniture and Fixtures"),
                            ("Land", "Land"),
                            ("Improvements", "Improvements"),
                            ("Vehicles", "Vehicles"),
                            ("Intangibles/Amortization", "Intangibles/Amortization"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "property_label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Location/property name for grouping (e.g. '821 Hillside Drive'). Blank for page 1 business assets.",
                        max_length=200,
                    ),
                ),
                ("date_acquired", models.DateField()),
                ("date_sold", models.DateField(blank=True, null=True)),
                ("cost_basis", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "business_pct",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("100.00"), max_digits=5
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("200DB", "200DB"),
                            ("150DB", "150DB"),
                            ("SL", "S/L"),
                            ("NONE", "None"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "convention",
                    models.CharField(
                        choices=[("HY", "HY"), ("MQ", "MQ"), ("MM", "MM")], max_length=5
                    ),
                ),
                (
                    "life",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Common lives: 3, 5, 7, 10, 15, 20, 27.5, 39",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "sec_179_elected",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "sec_179_prior",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "bonus_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Auto-suggested based on date_acquired per OBBBA rules, user can override.",
                        max_digits=5,
                    ),
                ),
                (
                    "bonus_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "prior_depreciation",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "current_depreciation",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                ("amt_method", models.CharField(blank=True, default="", max_length=10)),
                (
                    "amt_life",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "amt_prior_depreciation",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "amt_current_depreciation",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "state_method",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                (
                    "state_life",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "state_prior_depreciation",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "state_current_depreciation",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "state_bonus_disallowed",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Federal bonus taken that state does not allow. Flows to GA-600S Schedule 1 as an addition.",
                        max_digits=12,
                    ),
                ),
                (
                    "flow_to",
                    models.CharField(
                        choices=[
                            ("page1", "Page 1 (Line 14)"),
                            ("8825", "Form 8825"),
                            ("sched_f", "Schedule F"),
                        ],
                        default="page1",
                        max_length=10,
                    ),
                ),
                ("is_listed_property", models.BooleanField(default=False)),
                ("vehicle_miles_total", models.IntegerField(blank=True, null=True)),
                ("vehicle_miles_business", models.IntegerField(blank=True, null=True)),
                ("is_amortization", models.BooleanField(default=False)),
                (
                    "amort_code",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Common codes: '197' (Section 197 intangibles), '195' (startup costs).",
                        max_length=20,
                    ),
                ),
                ("amort_months", models.IntegerField(blank=True, null=True)),
                ("imported_from_lacerte", models.BooleanField(default=False)),
                ("lacerte_asset_no", models.IntegerField(blank=True, null=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rental_property",
                    models.ForeignKey(
                        blank=True,
                        help_text="Only used when flow_to = '8825'.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="depreciation_assets",
                        to="returns.rentalproperty",
                    ),
                ),
                (
                    "tax_return",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="depreciation_assets",
                        to="returns.taxreturn",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "asset_number"],
            },
        ),
    ]
