# Generated by Django 5.2.11 on 2026-03-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("returns", "0024_add_depreciation_asset"),
    ]

    operations = [
        migrations.AlterField(
            model_name="depreciationasset",
            name="description",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
