# Generated by Django 5.2.11 on 2026-03-10 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("returns", "0025_fix_depreciation_description_blank"),
    ]

    operations = [
        migrations.AddField(
            model_name="depreciationasset",
            name="depreciation_recapture",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Ordinary income recapture (Section 1245/1250).",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="depreciationasset",
            name="expenses_of_sale",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="depreciationasset",
            name="gain_loss_on_sale",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Computed: sales_price - (cost_basis - total_depreciation) - expenses_of_sale.",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="depreciationasset",
            name="sales_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="depreciationasset",
            name="date_acquired",
            field=models.DateField(blank=True, null=True),
        ),
    ]
