# Generated by Django 5.2.11 on 2026-03-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("returns", "0026_add_depreciation_disposal_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="depreciationasset",
            name="amt_capital_gain",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="depreciationasset",
            name="amt_depreciation_recapture",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="depreciationasset",
            name="amt_gain_loss_on_sale",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="depreciationasset",
            name="capital_gain",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Computed: total_gain - depreciation_recapture.",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="depreciationasset",
            name="gain_loss_on_sale",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Computed: sales_price - adjusted_basis - expenses_of_sale.",
                max_digits=12,
                null=True,
            ),
        ),
    ]
