# Generated by Django 5.2.11 on 2026-03-11 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("returns", "0027_add_amt_disposal_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formdefinition",
            name="code",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name="formdefinition",
            unique_together={("code", "tax_year_applicable")},
        ),
    ]
