# Generated by Django 5.2.11 on 2026-03-14 21:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0008_taxyear_filing_states"),
        ("returns", "0028_year_scope_form_definition"),
    ]

    operations = [
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "ssn",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="SSN or TIN (formatted XXX-XX-XXXX)",
                        max_length=11,
                    ),
                ),
                (
                    "address_line1",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "address_line2",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("city", models.CharField(blank=True, default="", max_length=100)),
                ("state", models.CharField(blank=True, default="", max_length=2)),
                ("zip_code", models.CharField(blank=True, default="", max_length=10)),
                (
                    "partner_type",
                    models.CharField(
                        choices=[
                            ("general", "General Partner"),
                            ("limited", "Limited Partner"),
                            ("llc_member", "LLC Member-Manager"),
                        ],
                        default="general",
                        help_text="General, Limited, or LLC Member-Manager.",
                        max_length=20,
                    ),
                ),
                (
                    "is_domestic",
                    models.BooleanField(
                        default=True,
                        help_text="True if the partner is a domestic (U.S.) partner.",
                    ),
                ),
                (
                    "is_individual",
                    models.BooleanField(
                        default=True,
                        help_text="True if the partner is an individual (not entity).",
                    ),
                ),
                (
                    "profit_pct",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="Partner's percentage share of profit.",
                        max_digits=7,
                    ),
                ),
                (
                    "loss_pct",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="Partner's percentage share of loss.",
                        max_digits=7,
                    ),
                ),
                (
                    "capital_pct",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="Partner's percentage share of capital.",
                        max_digits=7,
                    ),
                ),
                (
                    "profit_pct_boy",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="Profit % at beginning of year.",
                        max_digits=7,
                    ),
                ),
                (
                    "loss_pct_boy",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="Loss % at beginning of year.",
                        max_digits=7,
                    ),
                ),
                (
                    "capital_pct_boy",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="Capital % at beginning of year.",
                        max_digits=7,
                    ),
                ),
                (
                    "gp_services",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Guaranteed payments for services (K-1 Box 4a).",
                        max_digits=15,
                    ),
                ),
                (
                    "gp_capital",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Guaranteed payments for use of capital (K-1 Box 4b).",
                        max_digits=15,
                    ),
                ),
                (
                    "distributions",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Cash and property distributions to this partner (K-1 Box 19).",
                        max_digits=15,
                    ),
                ),
                (
                    "liability_recourse",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Partner's share of recourse liabilities.",
                        max_digits=15,
                    ),
                ),
                (
                    "liability_qnr",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Partner's share of qualified nonrecourse financing.",
                        max_digits=15,
                    ),
                ),
                (
                    "liability_nonrecourse",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Partner's share of nonrecourse liabilities.",
                        max_digits=15,
                    ),
                ),
                (
                    "capital_account_boy",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Capital account at beginning of year.",
                        max_digits=15,
                    ),
                ),
                (
                    "capital_contributed",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Capital contributed during the year.",
                        max_digits=15,
                    ),
                ),
                (
                    "current_year_increase",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Current year increase (net income).",
                        max_digits=15,
                    ),
                ),
                (
                    "withdrawals",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Withdrawals & distributions.",
                        max_digits=15,
                    ),
                ),
                (
                    "capital_account_eoy",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Capital account at end of year.",
                        max_digits=15,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the partner was active during the tax year.",
                    ),
                ),
                ("sort_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "linked_client",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to a client record if this partner is also a client.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="partner_links",
                        to="clients.client",
                    ),
                ),
                (
                    "tax_return",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partners",
                        to="returns.taxreturn",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="PartnerAllocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ordinary", "Ordinary income/loss"),
                            ("rental_re", "Net rental real estate income/loss"),
                            ("other_rental", "Other rental income/loss"),
                            ("interest", "Interest income"),
                            ("dividends", "Dividends"),
                            ("royalties", "Royalties"),
                            ("st_capital", "Short-term capital gain/loss"),
                            ("lt_capital", "Long-term capital gain/loss"),
                            ("sec_1231", "Section 1231 gain/loss"),
                            ("sec_179", "Section 179 deduction"),
                            ("charitable", "Charitable contributions"),
                            ("distributions", "Distributions"),
                            ("capital", "Capital (for capital account tracking)"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Allocation percentage for this category (0-100).",
                        max_digits=7,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="returns.partner",
                    ),
                ),
                (
                    "tax_return",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partner_allocations",
                        to="returns.taxreturn",
                    ),
                ),
            ],
            options={
                "ordering": ["category", "partner__sort_order"],
                "unique_together": {("tax_return", "partner", "category")},
            },
        ),
    ]
