# Generated by Django 5.2.11 on 2026-03-21 20:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0008_taxyear_filing_states"),
        ("firms", "0003_add_print_package"),
        ("returns", "0029_partner_and_allocation_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="taxreturn",
            index=models.Index(fields=["status"], name="returns_tax_status_dc24ab_idx"),
        ),
        migrations.AddIndex(
            model_name="taxreturn",
            index=models.Index(
                fields=["-updated_at"], name="returns_tax_updated_4ee8b6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taxreturn",
            index=models.Index(
                fields=["-created_at"], name="returns_tax_created_8d31c5_idx"
            ),
        ),
    ]
