# Generated by Django 5.2.11 on 2026-03-29 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("returns", "0030_taxreturn_returns_tax_status_dc24ab_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="depreciationasset",
            name="recapture_type",
            field=models.CharField(
                choices=[
                    ("auto", "Auto-detect"),
                    ("1245", "Section 1245 (personal property)"),
                    ("1250", "Section 1250 (real property)"),
                ],
                default="auto",
                help_text="Controls recapture calculation on disposition. Auto-detect uses group_label and life to determine type.",
                max_length=4,
            ),
        ),
    ]
