# Generated by Django 5.2.11 on 2026-04-12 23:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("returns", "0031_add_recapture_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="InterestIncome",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("payer_name", models.CharField(max_length=255)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="1099-INT Box 1: Interest income.",
                        max_digits=15,
                    ),
                ),
                (
                    "is_tax_exempt",
                    models.BooleanField(
                        default=False,
                        help_text="True if this is tax-exempt interest (Box 8).",
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tax_return",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interest_incomes",
                        to="returns.taxreturn",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "payer_name"],
            },
        ),
        migrations.CreateModel(
            name="Taxpayer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "filing_status",
                    models.CharField(
                        choices=[
                            ("single", "Single"),
                            ("mfj", "Married Filing Jointly"),
                            ("mfs", "Married Filing Separately"),
                            ("hoh", "Head of Household"),
                            ("qss", "Qualifying Surviving Spouse"),
                        ],
                        default="single",
                        max_length=10,
                    ),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "middle_initial",
                    models.CharField(blank=True, default="", max_length=1),
                ),
                ("last_name", models.CharField(blank=True, default="", max_length=100)),
                (
                    "ssn",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="SSN in XXX-XX-XXXX format.",
                        max_length=11,
                    ),
                ),
                (
                    "spouse_first_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "spouse_middle_initial",
                    models.CharField(blank=True, default="", max_length=1),
                ),
                (
                    "spouse_last_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "spouse_ssn",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Spouse SSN in XXX-XX-XXXX format.",
                        max_length=11,
                    ),
                ),
                (
                    "address_line1",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "address_line2",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("city", models.CharField(blank=True, default="", max_length=100)),
                ("state", models.CharField(blank=True, default="", max_length=2)),
                ("zip_code", models.CharField(blank=True, default="", max_length=10)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "occupation",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "spouse_occupation",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "standard_deduction_override",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Override standard deduction. If blank, filing-status default is used.",
                        max_digits=15,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tax_return",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taxpayer",
                        to="returns.taxreturn",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="W2Income",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("employer_name", models.CharField(max_length=255)),
                (
                    "employer_ein",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "wages",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Box 1: Wages, tips, other compensation.",
                        max_digits=15,
                    ),
                ),
                (
                    "federal_tax_withheld",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Box 2: Federal income tax withheld.",
                        max_digits=15,
                    ),
                ),
                (
                    "social_security_wages",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Box 3: Social security wages.",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "social_security_tax",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Box 4: Social security tax withheld.",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "medicare_wages",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Box 5: Medicare wages and tips.",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "medicare_tax",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Box 6: Medicare tax withheld.",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "state_wages",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Box 16: State wages, tips, etc.",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "state_tax_withheld",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Box 17: State income tax.",
                        max_digits=15,
                        null=True,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tax_return",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="w2_incomes",
                        to="returns.taxreturn",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "employer_name"],
            },
        ),
    ]
