# Generated by Django 5.2.11 on 2026-04-21 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("returns", "0032_add_1040_individual_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxpayer",
            name="spouse_date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
    ]
