# Generated by Django 5.2.11 on 2026-05-07 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("returns", "0033_add_spouse_date_of_birth"),
    ]

    operations = [
        migrations.AddField(
            model_name="w2income",
            name="employer_city",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="w2income",
            name="employer_state",
            field=models.CharField(blank=True, default="", max_length=2),
        ),
        migrations.AddField(
            model_name="w2income",
            name="employer_street",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="w2income",
            name="employer_zip",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AddField(
            model_name="w2income",
            name="state_box15",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Box 15: State code (2-letter).",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="w2income",
            name="state_id_number",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Box 15: Employer's state ID number.",
                max_length=30,
            ),
        ),
    ]
