# Generated by Django 5.2.11 on 2026-05-20 14:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("returns", "0034_w2income_employer_snapshot_and_box15"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dependent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "middle_initial",
                    models.CharField(blank=True, default="", max_length=1),
                ),
                ("last_name", models.CharField(blank=True, default="", max_length=100)),
                (
                    "ssn",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="SSN in XXX-XX-XXXX format.",
                        max_length=11,
                    ),
                ),
                (
                    "relationship",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "ctc_override",
                    models.BooleanField(
                        default=None,
                        help_text="None = use computed (under 17 at year-end). True/False overrides.",
                        null=True,
                    ),
                ),
                (
                    "odc_override",
                    models.BooleanField(
                        default=None,
                        help_text="None = use computed (dependent and not CTC-eligible). True/False overrides.",
                        null=True,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tax_return",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dependents",
                        to="returns.taxreturn",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "created_at"],
            },
        ),
    ]
