# Generated by Django 5.2.11 on 2026-05-20 15:41
# Edited to add RunPython data migration between AddField and RemoveField
# operations so old fields are readable when the data is split.

from django.db import migrations, models


def split_amount_into_interest_fields(apps, schema_editor):
    """Copy `amount` into either `interest_income` or `tax_exempt_interest`."""
    InterestIncome = apps.get_model("returns", "InterestIncome")
    for ii in InterestIncome.objects.all():
        if ii.is_tax_exempt:
            ii.tax_exempt_interest = ii.amount
            ii.interest_income = 0
        else:
            ii.interest_income = ii.amount
            ii.tax_exempt_interest = 0
        ii.save(update_fields=["interest_income", "tax_exempt_interest"])


def collapse_interest_fields_into_amount(apps, schema_editor):
    """Reverse migration. Ambiguous when both fields are non-zero — picks the larger."""
    InterestIncome = apps.get_model("returns", "InterestIncome")
    for ii in InterestIncome.objects.all():
        if ii.tax_exempt_interest and not ii.interest_income:
            ii.amount = ii.tax_exempt_interest
            ii.is_tax_exempt = True
        elif ii.tax_exempt_interest and ii.interest_income:
            if ii.tax_exempt_interest > ii.interest_income:
                ii.amount = ii.tax_exempt_interest
                ii.is_tax_exempt = True
            else:
                ii.amount = ii.interest_income
                ii.is_tax_exempt = False
        else:
            ii.amount = ii.interest_income
            ii.is_tax_exempt = False
        ii.save(update_fields=["amount", "is_tax_exempt"])


class Migration(migrations.Migration):

    dependencies = [
        ("returns", "0035_add_dependent_model"),
    ]

    operations = [
        # ── 1. Add all new fields first (so RunPython can write to them) ──────
        migrations.AddField(
            model_name="interestincome",
            name="bond_premium",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="interestincome",
            name="cusip_number",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="interestincome",
            name="early_withdrawal_penalty",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="interestincome",
            name="federal_tax_withheld",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="interestincome",
            name="foreign_country",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="interestincome",
            name="foreign_tax_paid",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="interestincome",
            name="interest_income",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="interestincome",
            name="investment_expenses",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="interestincome",
            name="market_discount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="interestincome",
            name="pab_interest",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="interestincome",
            name="payer_city",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="interestincome",
            name="payer_ein",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="interestincome",
            name="payer_state",
            field=models.CharField(blank=True, default="", max_length=2),
        ),
        migrations.AddField(
            model_name="interestincome",
            name="payer_street",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="interestincome",
            name="payer_zip",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AddField(
            model_name="interestincome",
            name="state_code",
            field=models.CharField(blank=True, default="", max_length=2),
        ),
        migrations.AddField(
            model_name="interestincome",
            name="state_id_number",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="interestincome",
            name="state_tax_withheld",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="interestincome",
            name="tax_exempt_bond_premium",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="interestincome",
            name="tax_exempt_interest",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="interestincome",
            name="treasury_bond_premium",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="interestincome",
            name="treasury_interest",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),

        # ── 2. Data migration — copy old fields into new fields ───────────────
        migrations.RunPython(
            split_amount_into_interest_fields,
            collapse_interest_fields_into_amount,
        ),

        # ── 3. Remove old fields (old columns still existed for RunPython) ────
        migrations.RemoveField(
            model_name="interestincome",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="interestincome",
            name="is_tax_exempt",
        ),
    ]
