# Generated by Django 5.2.11 on 2026-05-20 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("returns", "0036_expand_interest_income"),
    ]

    operations = [
        migrations.AddField(
            model_name="w2income",
            name="allocated_tips",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="w2income",
            name="dependent_care_benefits",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="w2income",
            name="local_income_tax",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="w2income",
            name="local_wages",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="w2income",
            name="locality_name",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="w2income",
            name="nonqualified_plans",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="w2income",
            name="retirement_plan",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="w2income",
            name="social_security_tips",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="w2income",
            name="statutory_employee",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="w2income",
            name="third_party_sick_pay",
            field=models.BooleanField(default=False),
        ),
    ]
