# Generated by Django 5.2.11 on 2026-05-20 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("returns", "0037_expand_w2_flat_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="w2income",
            name="allocated_tips",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Box 8: Allocated tips.",
                max_digits=15,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="w2income",
            name="dependent_care_benefits",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Box 10: Dependent care benefits.",
                max_digits=15,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="w2income",
            name="local_income_tax",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Box 19: Local income tax.",
                max_digits=15,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="w2income",
            name="local_wages",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Box 18: Local wages, tips, etc.",
                max_digits=15,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="w2income",
            name="locality_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Box 20: Locality name.",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="w2income",
            name="nonqualified_plans",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Box 11: Nonqualified plans.",
                max_digits=15,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="w2income",
            name="retirement_plan",
            field=models.BooleanField(
                default=False, help_text="Box 13: Retirement plan."
            ),
        ),
        migrations.AlterField(
            model_name="w2income",
            name="social_security_tips",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Box 7: Social security tips.",
                max_digits=15,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="w2income",
            name="statutory_employee",
            field=models.BooleanField(
                default=False, help_text="Box 13: Statutory employee."
            ),
        ),
        migrations.AlterField(
            model_name="w2income",
            name="third_party_sick_pay",
            field=models.BooleanField(
                default=False, help_text="Box 13: Third-party sick pay."
            ),
        ),
    ]
