# Generated by Django 5.2.11 on 2026-05-20 16:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("returns", "0038_alter_w2income_help_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="W2Box12Entry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("A", "A — Uncollected SS tax on tips"),
                            ("B", "B — Uncollected Medicare tax on tips"),
                            ("C", "C — Taxable cost of GTL > $50K"),
                            ("D", "D — 401(k) elective deferrals"),
                            ("E", "E — 403(b) elective deferrals"),
                            ("F", "F — 408(k)(6) elective deferrals"),
                            ("G", "G — 457(b) elective deferrals"),
                            ("H", "H — 501(c)(18)(D) elective deferrals"),
                            ("J", "J — Nontaxable sick pay"),
                            ("K", "K — 20% excise tax on excess golden parachute"),
                            (
                                "L",
                                "L — Substantiated employee business expense reimbursements",
                            ),
                            ("M", "M — Uncollected SS tax on GTL"),
                            ("N", "N — Uncollected Medicare tax on GTL"),
                            (
                                "P",
                                "P — Excludable moving expense reimbursements (active duty)",
                            ),
                            ("Q", "Q — Nontaxable combat pay"),
                            ("R", "R — Employer contributions to Archer MSA"),
                            (
                                "S",
                                "S — Employee salary reduction contributions to SIMPLE",
                            ),
                            ("T", "T — Adoption benefits"),
                            (
                                "V",
                                "V — Income from exercise of nonstatutory stock options",
                            ),
                            ("W", "W — Employer contributions to HSA"),
                            (
                                "Y",
                                "Y — Deferrals under 409A nonqualified deferred comp plan",
                            ),
                            ("Z", "Z — Income under 409A"),
                            ("AA", "AA — Designated Roth contributions under 401(k)"),
                            ("BB", "BB — Designated Roth contributions under 403(b)"),
                            ("DD", "DD — Cost of employer-sponsored health coverage"),
                            ("EE", "EE — Designated Roth contributions under 457(b)"),
                            ("FF", "FF — Permitted benefits under QSEHRA"),
                            ("GG", "GG — Income from qualified equity grants"),
                            (
                                "HH",
                                "HH — Aggregate deferrals under section 83(i) elections",
                            ),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "w2_income",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="box_12_entries",
                        to="returns.w2income",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="W2Box14Entry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("description", models.CharField(max_length=100)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "w2_income",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="box_14_entries",
                        to="returns.w2income",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "created_at"],
            },
        ),
    ]
