# Generated by Django 5.2.11 on 2026-05-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("returns", "0039_add_w2_box_entries"),
    ]

    operations = [
        migrations.AlterField(
            model_name="w2box14entry",
            name="description",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
