# Generated by Django 5.2.11 on 2026-05-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("returns", "0040_w2box14_description_blank"),
    ]

    operations = [
        migrations.AddField(
            model_name="dependent",
            name="citizenship_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("us_citizen", "U.S. citizen"),
                    ("us_national", "U.S. national"),
                    ("us_resident_alien", "U.S. resident alien"),
                    ("nonresident_alien", "Nonresident alien"),
                    ("mexico_canada_resident", "Resident of Mexico or Canada"),
                ],
                default="",
                help_text="Spec fact `dep_citizenship_status`. CTC/ODC require US citizen / national / resident alien per §152(b)(3).",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="dependent",
            name="filed_joint_return",
            field=models.BooleanField(
                default=False,
                help_text="Spec fact `dep_filed_joint_return`. CTC fails if True (joint-return-only-for-refund exception assumed resolved upstream).",
            ),
        ),
        migrations.AddField(
            model_name="dependent",
            name="is_permanently_disabled",
            field=models.BooleanField(
                default=False, help_text="Spec fact `dep_is_permanently_disabled`."
            ),
        ),
        migrations.AddField(
            model_name="dependent",
            name="months_resided_with_taxpayer",
            field=models.IntegerField(
                blank=True,
                help_text="Spec fact `dep_months_resided_with_taxpayer`. CTC requires > 6.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="dependent",
            name="provided_over_half_own_support",
            field=models.BooleanField(
                default=False,
                help_text="Spec fact `dep_provided_over_half_own_support`. CTC fails if True.",
            ),
        ),
        migrations.AddField(
            model_name="dependent",
            name="tin_type",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "valid_ssn",
                        "Valid SSN (work-authorized, issued before due date)",
                    ),
                    ("itin", "ITIN"),
                    ("atin", "ATIN (adoption taxpayer ID)"),
                    ("none", "No TIN"),
                ],
                default="",
                help_text="Spec fact `dep_tin_type`. CTC requires `valid_ssn`; ODC accepts `valid_ssn` / `itin` / `atin`.",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="dependent",
            name="relationship",
            field=models.CharField(
                blank=True,
                choices=[
                    ("child", "Son / daughter"),
                    ("descendant_of_child", "Grandchild / descendant of child"),
                    ("sibling", "Brother / sister"),
                    ("step_sibling", "Stepbrother / stepsister"),
                    ("descendant_of_sibling", "Niece / nephew"),
                    ("foster_child", "Eligible foster child"),
                    ("adopted_child", "Adopted child"),
                    ("other", "Other (does NOT qualify as CTC qualifying child)"),
                ],
                default="",
                help_text="Dependent's relationship to the taxpayer. Spec fact key `dep_relationship_code`. CTC qualifying-child test fails when 'other'.",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="dependent",
            name="ssn",
            field=models.CharField(
                blank=True,
                default="",
                help_text="SSN in XXX-XX-XXXX format. Display only — TIN type for CTC/ODC eligibility lives on `tin_type`.",
                max_length=11,
            ),
        ),
    ]
