# Generated by Django 5.2.11 on 2026-05-27 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("returns", "0041_expand_dependent_8812"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxpayer",
            name="additional_medicare_tax_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Placeholder — Form 8959 line 7. Spec fact `additional_medicare_tax_amount`.",
                max_digits=15,
            ),
        ),
        migrations.AddField(
            model_name="taxpayer",
            name="claims_credits_requiring_worksheet_b",
            field=models.BooleanField(
                default=False,
                help_text="Spec fact `claims_credits_requiring_worksheet_b` (Form 8396 / 8839 / 5695 Part I / 8859 present).",
            ),
        ),
        migrations.AddField(
            model_name="taxpayer",
            name="deductible_se_tax_half",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Placeholder — ½ SE tax (Schedule 1 line 15). Spec fact `deductible_se_tax_half`.",
                max_digits=15,
            ),
        ),
        migrations.AddField(
            model_name="taxpayer",
            name="eitc_claimed",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Placeholder — Form 1040 Line 27a. Spec fact `eitc_claimed`.",
                max_digits=15,
            ),
        ),
        migrations.AddField(
            model_name="taxpayer",
            name="excess_ss_rrta_withheld",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Placeholder — Schedule 3 line 11. Spec fact `excess_ss_rrta_withheld`.",
                max_digits=15,
            ),
        ),
        migrations.AddField(
            model_name="taxpayer",
            name="files_form_2555",
            field=models.BooleanField(
                default=False,
                help_text="Spec fact `files_form_2555`. ACTC = $0 when True (CTC/ODC still allowed).",
            ),
        ),
        migrations.AddField(
            model_name="taxpayer",
            name="form_2555_excluded_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Spec fact `form_2555_excluded_amount` (lines 45 + 50 combined).",
                max_digits=15,
            ),
        ),
        migrations.AddField(
            model_name="taxpayer",
            name="form_4563_excluded_income",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Spec fact `form_4563_excluded_income` (line 15 — American Samoa).",
                max_digits=15,
            ),
        ),
        migrations.AddField(
            model_name="taxpayer",
            name="nontaxable_combat_pay",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Spec fact `nontaxable_combat_pay` (Form 1040 Line 18b).",
                max_digits=15,
            ),
        ),
        migrations.AddField(
            model_name="taxpayer",
            name="other_employment_taxes",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Placeholder — Schedule 2 line 13. Spec fact `other_employment_taxes`.",
                max_digits=15,
            ),
        ),
        migrations.AddField(
            model_name="taxpayer",
            name="puerto_rico_excluded_income",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Spec fact `puerto_rico_excluded_income`.",
                max_digits=15,
            ),
        ),
        migrations.AddField(
            model_name="taxpayer",
            name="schedule_3_pre_ctc_credits_total",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Placeholder — Schedule 3 credits applied BEFORE CTC (sum of lines 1, 2, 3, 4, 5b, 6d, 6f, 6l, 6m). Spec fact `schedule_3_pre_ctc_credits_total`.",
                max_digits=15,
            ),
        ),
        migrations.AddField(
            model_name="taxpayer",
            name="se_tax_total",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Placeholder — SE tax total (Schedule 2 line 5). Spec fact `se_tax_total`.",
                max_digits=15,
            ),
        ),
        migrations.AddField(
            model_name="taxpayer",
            name="spouse_has_ssn_or_itin_by_due_date",
            field=models.BooleanField(
                default=True,
                help_text="Spec fact `spouse_has_ssn_or_itin_by_due_date` (MFJ only).",
            ),
        ),
        migrations.AddField(
            model_name="taxpayer",
            name="spouse_has_valid_ssn",
            field=models.BooleanField(
                default=True,
                help_text="Spec fact `spouse_has_valid_ssn` (MFJ only). At least one of TP/SP must have a valid SSN for any CTC/ACTC/ODC.",
            ),
        ),
        migrations.AddField(
            model_name="taxpayer",
            name="taxpayer_has_rrta_taxes",
            field=models.BooleanField(
                default=False,
                help_text="Spec fact `taxpayer_has_rrta_taxes` (Tier 1 RRTA via W-2 box 14 or CT-2).",
            ),
        ),
        migrations.AddField(
            model_name="taxpayer",
            name="taxpayer_has_valid_ssn",
            field=models.BooleanField(
                default=True,
                help_text="Spec fact `taxpayer_has_valid_ssn`. CTC/ACTC/ODC zeroed when False.",
            ),
        ),
        migrations.AddField(
            model_name="taxpayer",
            name="unreported_ss_medicare_tax",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Placeholder — Schedule 2 line 6 (Forms 4137 / 8919). Spec fact `unreported_ss_medicare_tax`.",
                max_digits=15,
            ),
        ),
    ]
