"""
Field map stub for f1040sf.pdf
Generated by extract_field_maps.py -- needs mapping.

Each entry maps a seed line mapping_key to the PDF AcroForm field name.
TODO: Map each field to the corresponding FormLine mapping_key.
"""

from . import AcroField, FieldMap

# PDF template: resources/irs_forms/2025/f1040sf.pdf
# Pages: 2
# Total AcroForm fields: 89

# --- All PDF AcroForm field names (for reference) ---
PDF_FIELDS = [
    "topmostSubform[0].Page1[0].CombField_LineB[0].f1_4[0]",
    "topmostSubform[0].Page1[0].CombField_LineD[0].f1_5[0]",
    "topmostSubform[0].Page1[0].LineC_ReadOrder[0].c1_1[0]",
    "topmostSubform[0].Page1[0].LineC_ReadOrder[0].c1_1[1]",
    "topmostSubform[0].Page1[0].Lines10-22[0].f1_23[0]",
    "topmostSubform[0].Page1[0].Lines10-22[0].f1_24[0]",
    "topmostSubform[0].Page1[0].Lines10-22[0].f1_25[0]",
    "topmostSubform[0].Page1[0].Lines10-22[0].f1_26[0]",
    "topmostSubform[0].Page1[0].Lines10-22[0].f1_27[0]",
    "topmostSubform[0].Page1[0].Lines10-22[0].f1_28[0]",
    "topmostSubform[0].Page1[0].Lines10-22[0].f1_29[0]",
    "topmostSubform[0].Page1[0].Lines10-22[0].f1_30[0]",
    "topmostSubform[0].Page1[0].Lines10-22[0].f1_31[0]",
    "topmostSubform[0].Page1[0].Lines10-22[0].f1_32[0]",
    "topmostSubform[0].Page1[0].Lines10-22[0].f1_33[0]",
    "topmostSubform[0].Page1[0].Lines10-22[0].f1_34[0]",
    "topmostSubform[0].Page1[0].Lines10-22[0].f1_35[0]",
    "topmostSubform[0].Page1[0].Lines10-22[0].f1_36[0]",
    "topmostSubform[0].Page1[0].c1_2[0]",
    "topmostSubform[0].Page1[0].c1_2[1]",
    "topmostSubform[0].Page1[0].c1_3[0]",
    "topmostSubform[0].Page1[0].c1_3[1]",
    "topmostSubform[0].Page1[0].c1_4[0]",
    "topmostSubform[0].Page1[0].c1_4[1]",
    "topmostSubform[0].Page1[0].c1_5[0]",
    "topmostSubform[0].Page1[0].c1_6[0]",
    "topmostSubform[0].Page1[0].c1_6[1]",
    "topmostSubform[0].Page1[0].f1_10[0]",
    "topmostSubform[0].Page1[0].f1_11[0]",
    "topmostSubform[0].Page1[0].f1_12[0]",
    "topmostSubform[0].Page1[0].f1_13[0]",
    "topmostSubform[0].Page1[0].f1_14[0]",
    "topmostSubform[0].Page1[0].f1_15[0]",
    "topmostSubform[0].Page1[0].f1_16[0]",
    "topmostSubform[0].Page1[0].f1_17[0]",
    "topmostSubform[0].Page1[0].f1_18[0]",
    "topmostSubform[0].Page1[0].f1_19[0]",
    "topmostSubform[0].Page1[0].f1_1[0]",
    "topmostSubform[0].Page1[0].f1_20[0]",
    "topmostSubform[0].Page1[0].f1_21[0]",
    "topmostSubform[0].Page1[0].f1_22[0]",
    "topmostSubform[0].Page1[0].f1_2[0]",
    "topmostSubform[0].Page1[0].f1_37[0]",
    "topmostSubform[0].Page1[0].f1_38[0]",
    "topmostSubform[0].Page1[0].f1_39[0]",
    "topmostSubform[0].Page1[0].f1_3[0]",
    "topmostSubform[0].Page1[0].f1_40[0]",
    "topmostSubform[0].Page1[0].f1_41[0]",
    "topmostSubform[0].Page1[0].f1_42[0]",
    "topmostSubform[0].Page1[0].f1_43[0]",
    "topmostSubform[0].Page1[0].f1_44[0]",
    "topmostSubform[0].Page1[0].f1_45[0]",
    "topmostSubform[0].Page1[0].f1_46[0]",
    "topmostSubform[0].Page1[0].f1_47[0]",
    "topmostSubform[0].Page1[0].f1_48[0]",
    "topmostSubform[0].Page1[0].f1_49[0]",
    "topmostSubform[0].Page1[0].f1_50[0]",
    "topmostSubform[0].Page1[0].f1_51[0]",
    "topmostSubform[0].Page1[0].f1_52[0]",
    "topmostSubform[0].Page1[0].f1_53[0]",
    "topmostSubform[0].Page1[0].f1_54[0]",
    "topmostSubform[0].Page1[0].f1_55[0]",
    "topmostSubform[0].Page1[0].f1_56[0]",
    "topmostSubform[0].Page1[0].f1_57[0]",
    "topmostSubform[0].Page1[0].f1_58[0]",
    "topmostSubform[0].Page1[0].f1_59[0]",
    "topmostSubform[0].Page1[0].f1_60[0]",
    "topmostSubform[0].Page1[0].f1_6[0]",
    "topmostSubform[0].Page1[0].f1_7[0]",
    "topmostSubform[0].Page1[0].f1_8[0]",
    "topmostSubform[0].Page1[0].f1_9[0]",
    "topmostSubform[0].Page2[0].Line38a_ReadOrder[0].f2_2[0]",
    "topmostSubform[0].Page2[0].Line39a_ReadOrder[0].f2_4[0]",
    "topmostSubform[0].Page2[0].Line40b_ReadOrder[0].f2_7[0]",
    "topmostSubform[0].Page2[0].Line45_ReadOrder[0].f2_13[0]",
    "topmostSubform[0].Page2[0].f2_10[0]",
    "topmostSubform[0].Page2[0].f2_11[0]",
    "topmostSubform[0].Page2[0].f2_12[0]",
    "topmostSubform[0].Page2[0].f2_14[0]",
    "topmostSubform[0].Page2[0].f2_15[0]",
    "topmostSubform[0].Page2[0].f2_16[0]",
    "topmostSubform[0].Page2[0].f2_17[0]",
    "topmostSubform[0].Page2[0].f2_18[0]",
    "topmostSubform[0].Page2[0].f2_1[0]",
    "topmostSubform[0].Page2[0].f2_3[0]",
    "topmostSubform[0].Page2[0].f2_5[0]",
    "topmostSubform[0].Page2[0].f2_6[0]",
    "topmostSubform[0].Page2[0].f2_8[0]",
    "topmostSubform[0].Page2[0].f2_9[0]",
]

# --- Header map (entity identification) ---
HEADER_MAP: FieldMap = {
    # "entity_name": AcroField("..."),
    # "ein": AcroField("..."),
}

# --- Field map (mapping_key -> PDF field) ---
FIELD_MAP: FieldMap = {
    # "LINE_KEY": AcroField("pdf_field_name", format="currency"),
}
