"""
Field map stub for f2553.pdf
Generated by extract_field_maps.py -- needs mapping.

Each entry maps a seed line mapping_key to the PDF AcroForm field name.
TODO: Map each field to the corresponding FormLine mapping_key.
"""

from . import AcroField, FieldMap

# PDF template: resources/irs_forms/2025/f2553.pdf
# Pages: 4
# Total AcroForm fields: 100

# --- All PDF AcroForm field names (for reference) ---
PDF_FIELDS = [
    "topmostSubform[0].Page1[0].NameAddress[0].f1_01[0]",
    "topmostSubform[0].Page1[0].NameAddress[0].f1_02[0]",
    "topmostSubform[0].Page1[0].NameAddress[0].f1_03[0]",
    "topmostSubform[0].Page1[0].c1_1[0]",
    "topmostSubform[0].Page1[0].c1_2[0]",
    "topmostSubform[0].Page1[0].c1_3[0]",
    "topmostSubform[0].Page1[0].c1_3[1]",
    "topmostSubform[0].Page1[0].c1_3[2]",
    "topmostSubform[0].Page1[0].c1_3[3]",
    "topmostSubform[0].Page1[0].c1_4[0]",
    "topmostSubform[0].Page1[0].f1_04[0]",
    "topmostSubform[0].Page1[0].f1_05[0]",
    "topmostSubform[0].Page1[0].f1_06[0]",
    "topmostSubform[0].Page1[0].f1_07[0]",
    "topmostSubform[0].Page1[0].f1_08[0]",
    "topmostSubform[0].Page1[0].f1_09[0]",
    "topmostSubform[0].Page1[0].f1_10[0]",
    "topmostSubform[0].Page1[0].f1_11[0]",
    "topmostSubform[0].Page1[0].f1_12[0]",
    "topmostSubform[0].Page1[0].f1_13[0]",
    "topmostSubform[0].Page1[0].f1_14[0]",
    "topmostSubform[0].Page1[0].f1_15[0]",
    "topmostSubform[0].Page1[0].f1_16[0]",
    "topmostSubform[0].Page1[0].f1_17[0]",
    "topmostSubform[0].Page1[0].f1_18[0]",
    "topmostSubform[0].Page1[0].f1_19[0]",
    "topmostSubform[0].Page1[0].f1_20[0]",
    "topmostSubform[0].Page1[0].f1_21[0]",
    "topmostSubform[0].Page2[0].Table_Part1[0].Row1[0].f2_03[0]",
    "topmostSubform[0].Page2[0].Table_Part1[0].Row1[0].f2_04[0]",
    "topmostSubform[0].Page2[0].Table_Part1[0].Row1[0].f2_05[0]",
    "topmostSubform[0].Page2[0].Table_Part1[0].Row1[0].f2_06[0]",
    "topmostSubform[0].Page2[0].Table_Part1[0].Row1[0].f2_07[0]",
    "topmostSubform[0].Page2[0].Table_Part1[0].Row1[0].f2_08[0]",
    "topmostSubform[0].Page2[0].Table_Part1[0].Row1[0].f2_09[0]",
    "topmostSubform[0].Page2[0].Table_Part1[0].Row2[0].f2_10[0]",
    "topmostSubform[0].Page2[0].Table_Part1[0].Row2[0].f2_11[0]",
    "topmostSubform[0].Page2[0].Table_Part1[0].Row2[0].f2_12[0]",
    "topmostSubform[0].Page2[0].Table_Part1[0].Row2[0].f2_13[0]",
    "topmostSubform[0].Page2[0].Table_Part1[0].Row2[0].f2_14[0]",
    "topmostSubform[0].Page2[0].Table_Part1[0].Row2[0].f2_15[0]",
    "topmostSubform[0].Page2[0].Table_Part1[0].Row2[0].f2_16[0]",
    "topmostSubform[0].Page2[0].Table_Part1[0].Row3[0].f2_17[0]",
    "topmostSubform[0].Page2[0].Table_Part1[0].Row3[0].f2_18[0]",
    "topmostSubform[0].Page2[0].Table_Part1[0].Row3[0].f2_19[0]",
    "topmostSubform[0].Page2[0].Table_Part1[0].Row3[0].f2_20[0]",
    "topmostSubform[0].Page2[0].Table_Part1[0].Row3[0].f2_21[0]",
    "topmostSubform[0].Page2[0].Table_Part1[0].Row3[0].f2_22[0]",
    "topmostSubform[0].Page2[0].Table_Part1[0].Row3[0].f2_23[0]",
    "topmostSubform[0].Page2[0].Table_Part1[0].Row4[0].f2_24[0]",
    "topmostSubform[0].Page2[0].Table_Part1[0].Row4[0].f2_25[0]",
    "topmostSubform[0].Page2[0].Table_Part1[0].Row4[0].f2_26[0]",
    "topmostSubform[0].Page2[0].Table_Part1[0].Row4[0].f2_27[0]",
    "topmostSubform[0].Page2[0].Table_Part1[0].Row4[0].f2_28[0]",
    "topmostSubform[0].Page2[0].Table_Part1[0].Row4[0].f2_29[0]",
    "topmostSubform[0].Page2[0].Table_Part1[0].Row4[0].f2_30[0]",
    "topmostSubform[0].Page2[0].Table_Part1[0].Row5[0].f2_31[0]",
    "topmostSubform[0].Page2[0].Table_Part1[0].Row5[0].f2_32[0]",
    "topmostSubform[0].Page2[0].Table_Part1[0].Row5[0].f2_33[0]",
    "topmostSubform[0].Page2[0].Table_Part1[0].Row5[0].f2_34[0]",
    "topmostSubform[0].Page2[0].Table_Part1[0].Row5[0].f2_35[0]",
    "topmostSubform[0].Page2[0].Table_Part1[0].Row5[0].f2_36[0]",
    "topmostSubform[0].Page2[0].Table_Part1[0].Row5[0].f2_37[0]",
    "topmostSubform[0].Page2[0].Table_Part1[0].Row6[0].f2_38[0]",
    "topmostSubform[0].Page2[0].Table_Part1[0].Row6[0].f2_39[0]",
    "topmostSubform[0].Page2[0].Table_Part1[0].Row6[0].f2_40[0]",
    "topmostSubform[0].Page2[0].Table_Part1[0].Row6[0].f2_41[0]",
    "topmostSubform[0].Page2[0].Table_Part1[0].Row6[0].f2_42[0]",
    "topmostSubform[0].Page2[0].Table_Part1[0].Row6[0].f2_43[0]",
    "topmostSubform[0].Page2[0].Table_Part1[0].Row6[0].f2_44[0]",
    "topmostSubform[0].Page2[0].Table_Part1[0].Row7[0].f2_45[0]",
    "topmostSubform[0].Page2[0].Table_Part1[0].Row7[0].f2_46[0]",
    "topmostSubform[0].Page2[0].Table_Part1[0].Row7[0].f2_47[0]",
    "topmostSubform[0].Page2[0].Table_Part1[0].Row7[0].f2_48[0]",
    "topmostSubform[0].Page2[0].Table_Part1[0].Row7[0].f2_49[0]",
    "topmostSubform[0].Page2[0].Table_Part1[0].Row7[0].f2_50[0]",
    "topmostSubform[0].Page2[0].Table_Part1[0].Row7[0].f2_51[0]",
    "topmostSubform[0].Page2[0].f2_01[0]",
    "topmostSubform[0].Page2[0].f2_02[0]",
    "topmostSubform[0].Page3[0].c3_1[0]",
    "topmostSubform[0].Page3[0].c3_1[1]",
    "topmostSubform[0].Page3[0].c3_1[2]",
    "topmostSubform[0].Page3[0].c3_2[0]",
    "topmostSubform[0].Page3[0].c3_3[0]",
    "topmostSubform[0].Page3[0].c3_4[0]",
    "topmostSubform[0].Page3[0].c3_5[0]",
    "topmostSubform[0].Page3[0].c3_5[1]",
    "topmostSubform[0].Page3[0].c3_6[0]",
    "topmostSubform[0].Page3[0].c3_7[0]",
    "topmostSubform[0].Page3[0].c3_8[0]",
    "topmostSubform[0].Page3[0].c3_9[0]",
    "topmostSubform[0].Page3[0].f3_01[0]",
    "topmostSubform[0].Page3[0].f3_02[0]",
    "topmostSubform[0].Page4[0].f4_01[0]",
    "topmostSubform[0].Page4[0].f4_02[0]",
    "topmostSubform[0].Page4[0].f4_03[0]",
    "topmostSubform[0].Page4[0].f4_04[0]",
    "topmostSubform[0].Page4[0].f4_05[0]",
    "topmostSubform[0].Page4[0].f4_06[0]",
    "topmostSubform[0].Page4[0].f4_07[0]",
]

# --- Header map (entity identification) ---
HEADER_MAP: FieldMap = {
    # "entity_name": AcroField("..."),
    # "ein": AcroField("..."),
}

# --- Field map (mapping_key -> PDF field) ---
FIELD_MAP: FieldMap = {
    # "LINE_KEY": AcroField("pdf_field_name", format="currency"),
}
