"""
Field map stub for f2848.pdf
Generated by extract_field_maps.py -- needs mapping.

Each entry maps a seed line mapping_key to the PDF AcroForm field name.
TODO: Map each field to the corresponding FormLine mapping_key.
"""

from . import AcroField, FieldMap

# PDF template: resources/irs_forms/2025/f2848.pdf
# Pages: 2
# Total AcroForm fields: 92

# --- All PDF AcroForm field names (for reference) ---
PDF_FIELDS = [
    "topmostSubform[0].Page1[0].AccessRecords[0]",
    "topmostSubform[0].Page1[0].AdditionalActs1[0]",
    "topmostSubform[0].Page1[0].AdditionalActs2[0]",
    "topmostSubform[0].Page1[0].AdditionalActs3[0]",
    "topmostSubform[0].Page1[0].AuthorizeDisclosure[0]",
    "topmostSubform[0].Page1[0].CAFNumber1[0]",
    "topmostSubform[0].Page1[0].CAFNumber2[0]",
    "topmostSubform[0].Page1[0].CAFNumber3[0]",
    "topmostSubform[0].Page1[0].CAFNumber4[0]",
    "topmostSubform[0].Page1[0].CheckForm[0]",
    "topmostSubform[0].Page1[0].FaxNo1[0]",
    "topmostSubform[0].Page1[0].FaxNo2[0]",
    "topmostSubform[0].Page1[0].FaxNo3[0]",
    "topmostSubform[0].Page1[0].FaxNo4[0]",
    "topmostSubform[0].Page1[0].NewAddress1[0]",
    "topmostSubform[0].Page1[0].NewAddress2[0]",
    "topmostSubform[0].Page1[0].NewAddress3[0]",
    "topmostSubform[0].Page1[0].NewAddress4[0]",
    "topmostSubform[0].Page1[0].NewFaxNo1[0]",
    "topmostSubform[0].Page1[0].NewFaxNo2[0]",
    "topmostSubform[0].Page1[0].NewFaxNo3[0]",
    "topmostSubform[0].Page1[0].NewFaxNo4[0]",
    "topmostSubform[0].Page1[0].NewTelephoneNo1[0]",
    "topmostSubform[0].Page1[0].NewTelephoneNo2[0]",
    "topmostSubform[0].Page1[0].NewTelephoneNo3[0]",
    "topmostSubform[0].Page1[0].NewTelephoneNo4[0]",
    "topmostSubform[0].Page1[0].OtherActs1[0]",
    "topmostSubform[0].Page1[0].OtherActs2[0]",
    "topmostSubform[0].Page1[0].OtherActs[0]",
    "topmostSubform[0].Page1[0].PTIN1[0]",
    "topmostSubform[0].Page1[0].PTIN2[0]",
    "topmostSubform[0].Page1[0].PTIN3[0]",
    "topmostSubform[0].Page1[0].PTIN4[0]",
    "topmostSubform[0].Page1[0].RepresentativesAddress1[0]",
    "topmostSubform[0].Page1[0].RepresentativesAddress2[0]",
    "topmostSubform[0].Page1[0].RepresentativesAddress3[0]",
    "topmostSubform[0].Page1[0].RepresentativesAddress4[0]",
    "topmostSubform[0].Page1[0].RepresentativesName1[0]",
    "topmostSubform[0].Page1[0].RepresentativesName2[0]",
    "topmostSubform[0].Page1[0].RepresentativesName3[0]",
    "topmostSubform[0].Page1[0].RepresentativesName4[0]",
    "topmostSubform[0].Page1[0].SentCopies1[0]",
    "topmostSubform[0].Page1[0].SentCopies2[0]",
    "topmostSubform[0].Page1[0].SignReturn[0]",
    "topmostSubform[0].Page1[0].SpecificUse[0]",
    "topmostSubform[0].Page1[0].SubtituteOrAdd[0]",
    "topmostSubform[0].Page1[0].Table_Line3[0].BodyRow1[0].Description1[0]",
    "topmostSubform[0].Page1[0].Table_Line3[0].BodyRow1[0].TaxForm1[0]",
    "topmostSubform[0].Page1[0].Table_Line3[0].BodyRow1[0].Years1[0]",
    "topmostSubform[0].Page1[0].Table_Line3[0].BodyRow2[0].Description2[0]",
    "topmostSubform[0].Page1[0].Table_Line3[0].BodyRow2[0].TaxForm2[0]",
    "topmostSubform[0].Page1[0].Table_Line3[0].BodyRow2[0].Years2[0]",
    "topmostSubform[0].Page1[0].Table_Line3[0].BodyRow3[0].Description3[0]",
    "topmostSubform[0].Page1[0].Table_Line3[0].BodyRow3[0].TaxForm3[0]",
    "topmostSubform[0].Page1[0].Table_Line3[0].BodyRow3[0].Years3[0]",
    "topmostSubform[0].Page1[0].TaxpayerAddress[0]",
    "topmostSubform[0].Page1[0].TaxpayerIDEIN[0]",
    "topmostSubform[0].Page1[0].TaxpayerIDITIN[0]",
    "topmostSubform[0].Page1[0].TaxpayerIDSSN[0]",
    "topmostSubform[0].Page1[0].TaxpayerName[0]",
    "topmostSubform[0].Page1[0].TaxpayerPlanNumber[0]",
    "topmostSubform[0].Page1[0].TaxpayerTelephone[0]",
    "topmostSubform[0].Page1[0].TelephoneNo1[0]",
    "topmostSubform[0].Page1[0].TelephoneNo2[0]",
    "topmostSubform[0].Page1[0].TelephoneNo3[0]",
    "topmostSubform[0].Page1[0].TelephoneNo4[0]",
    "topmostSubform[0].Page2[0].PrintNameTaxpayer[0]",
    "topmostSubform[0].Page2[0].PrintName[0]",
    "topmostSubform[0].Page2[0].RetentionRevocation[1]",
    "topmostSubform[0].Page2[0].SpecificDeletions1[0]",
    "topmostSubform[0].Page2[0].SpecificDeletions2[0]",
    "topmostSubform[0].Page2[0].Table_PartII[0].BodyRow1[0].Bar1[0]",
    "topmostSubform[0].Page2[0].Table_PartII[0].BodyRow1[0].Date1[0]",
    "topmostSubform[0].Page2[0].Table_PartII[0].BodyRow1[0].Designation1[0]",
    "topmostSubform[0].Page2[0].Table_PartII[0].BodyRow1[0].Jurisdiction1[0]",
    "topmostSubform[0].Page2[0].Table_PartII[0].BodyRow1[0].Signature1[0]",
    "topmostSubform[0].Page2[0].Table_PartII[0].BodyRow2[0].Bar2[0]",
    "topmostSubform[0].Page2[0].Table_PartII[0].BodyRow2[0].Date2[0]",
    "topmostSubform[0].Page2[0].Table_PartII[0].BodyRow2[0].Designation2[0]",
    "topmostSubform[0].Page2[0].Table_PartII[0].BodyRow2[0].Jurisdiction2[0]",
    "topmostSubform[0].Page2[0].Table_PartII[0].BodyRow2[0].Signature2[0]",
    "topmostSubform[0].Page2[0].Table_PartII[0].BodyRow3[0].Bar3[0]",
    "topmostSubform[0].Page2[0].Table_PartII[0].BodyRow3[0].Date3[0]",
    "topmostSubform[0].Page2[0].Table_PartII[0].BodyRow3[0].Designation3[0]",
    "topmostSubform[0].Page2[0].Table_PartII[0].BodyRow3[0].Jurisdiction3[0]",
    "topmostSubform[0].Page2[0].Table_PartII[0].BodyRow3[0].Signature3[0]",
    "topmostSubform[0].Page2[0].Table_PartII[0].BodyRow4[0].Bar4[0]",
    "topmostSubform[0].Page2[0].Table_PartII[0].BodyRow4[0].Date4[0]",
    "topmostSubform[0].Page2[0].Table_PartII[0].BodyRow4[0].Designation4[0]",
    "topmostSubform[0].Page2[0].Table_PartII[0].BodyRow4[0].Jurisdiction4[0]",
    "topmostSubform[0].Page2[0].Table_PartII[0].BodyRow4[0].Signature4[0]",
    "topmostSubform[0].Page2[0].Title[0]",
]

# --- Header map (entity identification) ---
HEADER_MAP: FieldMap = {
    # "entity_name": AcroField("..."),
    # "ein": AcroField("..."),
}

# --- Field map (mapping_key -> PDF field) ---
FIELD_MAP: FieldMap = {
    # "LINE_KEY": AcroField("pdf_field_name", format="currency"),
}
