"""
Field map stub for f8050.pdf
Generated by extract_field_maps.py -- needs mapping.

Each entry maps a seed line mapping_key to the PDF AcroForm field name.
TODO: Map each field to the corresponding FormLine mapping_key.
"""

from . import AcroField, FieldMap

# PDF template: resources/irs_forms/2025/f8050.pdf
# Pages: 1
# Total AcroForm fields: 7

# --- All PDF AcroForm field names (for reference) ---
PDF_FIELDS = [
    "topmostSubform[0].Page1[0].AccountNo[0].f1_5[0]",
    "topmostSubform[0].Page1[0].Line1_ReadOrder[0].RoutingNo[0].f1_4[0]",
    "topmostSubform[0].Page1[0].c1_1[0]",
    "topmostSubform[0].Page1[0].c1_1[1]",
    "topmostSubform[0].Page1[0].f1_1[0]",
    "topmostSubform[0].Page1[0].f1_2[0]",
    "topmostSubform[0].Page1[0].f1_3[0]",
]

# --- Header map (entity identification) ---
HEADER_MAP: FieldMap = {
    # "entity_name": AcroField("..."),
    # "ein": AcroField("..."),
}

# --- Field map (mapping_key -> PDF field) ---
FIELD_MAP: FieldMap = {
    # "LINE_KEY": AcroField("pdf_field_name", format="currency"),
}
