"""
Field map stub for f8824.pdf
Generated by extract_field_maps.py -- needs mapping.

Each entry maps a seed line mapping_key to the PDF AcroForm field name.
TODO: Map each field to the corresponding FormLine mapping_key.
"""

from . import AcroField, FieldMap

# PDF template: resources/irs_forms/2025/f8824.pdf
# Pages: 2
# Total AcroForm fields: 63

# --- All PDF AcroForm field names (for reference) ---
PDF_FIELDS = [
    "topmostSubform[0].Page1[0].c1_1[0]",
    "topmostSubform[0].Page1[0].c1_1[1]",
    "topmostSubform[0].Page1[0].c1_2[0]",
    "topmostSubform[0].Page1[0].c1_2[1]",
    "topmostSubform[0].Page1[0].c1_3[0]",
    "topmostSubform[0].Page1[0].c1_3[1]",
    "topmostSubform[0].Page1[0].c1_4[0]",
    "topmostSubform[0].Page1[0].c1_4[1]",
    "topmostSubform[0].Page1[0].c1_4[2]",
    "topmostSubform[0].Page1[0].f1_10[0]",
    "topmostSubform[0].Page1[0].f1_11[0]",
    "topmostSubform[0].Page1[0].f1_12[0]",
    "topmostSubform[0].Page1[0].f1_13[0]",
    "topmostSubform[0].Page1[0].f1_14[0]",
    "topmostSubform[0].Page1[0].f1_1[0]",
    "topmostSubform[0].Page1[0].f1_2[0]",
    "topmostSubform[0].Page1[0].f1_3[0]",
    "topmostSubform[0].Page1[0].f1_4[0]",
    "topmostSubform[0].Page1[0].f1_5[0]",
    "topmostSubform[0].Page1[0].f1_6[0]",
    "topmostSubform[0].Page1[0].f1_7[0]",
    "topmostSubform[0].Page1[0].f1_8[0]",
    "topmostSubform[0].Page1[0].f1_9[0]",
    "topmostSubform[0].Page2[0].f2_10[0]",
    "topmostSubform[0].Page2[0].f2_11[0]",
    "topmostSubform[0].Page2[0].f2_12[0]",
    "topmostSubform[0].Page2[0].f2_13[0]",
    "topmostSubform[0].Page2[0].f2_14[0]",
    "topmostSubform[0].Page2[0].f2_16[0]",
    "topmostSubform[0].Page2[0].f2_17[0]",
    "topmostSubform[0].Page2[0].f2_18[0]",
    "topmostSubform[0].Page2[0].f2_19[0]",
    "topmostSubform[0].Page2[0].f2_1[0]",
    "topmostSubform[0].Page2[0].f2_20[0]",
    "topmostSubform[0].Page2[0].f2_21[0]",
    "topmostSubform[0].Page2[0].f2_22[0]",
    "topmostSubform[0].Page2[0].f2_23[0]",
    "topmostSubform[0].Page2[0].f2_24[0]",
    "topmostSubform[0].Page2[0].f2_25[0]",
    "topmostSubform[0].Page2[0].f2_26[0]",
    "topmostSubform[0].Page2[0].f2_27[0]",
    "topmostSubform[0].Page2[0].f2_28[0]",
    "topmostSubform[0].Page2[0].f2_29[0]",
    "topmostSubform[0].Page2[0].f2_2[0]",
    "topmostSubform[0].Page2[0].f2_30[0]",
    "topmostSubform[0].Page2[0].f2_31[0]",
    "topmostSubform[0].Page2[0].f2_32[0]",
    "topmostSubform[0].Page2[0].f2_33[0]",
    "topmostSubform[0].Page2[0].f2_34[0]",
    "topmostSubform[0].Page2[0].f2_35[0]",
    "topmostSubform[0].Page2[0].f2_36[0]",
    "topmostSubform[0].Page2[0].f2_37[0]",
    "topmostSubform[0].Page2[0].f2_38[0]",
    "topmostSubform[0].Page2[0].f2_39[0]",
    "topmostSubform[0].Page2[0].f2_3[0]",
    "topmostSubform[0].Page2[0].f2_40[0]",
    "topmostSubform[0].Page2[0].f2_41[0]",
    "topmostSubform[0].Page2[0].f2_4[0]",
    "topmostSubform[0].Page2[0].f2_5[0]",
    "topmostSubform[0].Page2[0].f2_6[0]",
    "topmostSubform[0].Page2[0].f2_7[0]",
    "topmostSubform[0].Page2[0].f2_8[0]",
    "topmostSubform[0].Page2[0].f2_9[0]",
]

# --- Header map (entity identification) ---
HEADER_MAP: FieldMap = {
    # "entity_name": AcroField("..."),
    # "ein": AcroField("..."),
}

# --- Field map (mapping_key -> PDF field) ---
FIELD_MAP: FieldMap = {
    # "LINE_KEY": AcroField("pdf_field_name", format="currency"),
}
