"""
Field map stub for f8995.pdf
Generated by extract_field_maps.py -- needs mapping.

Each entry maps a seed line mapping_key to the PDF AcroForm field name.
TODO: Map each field to the corresponding FormLine mapping_key.
"""

from . import AcroField, FieldMap

# PDF template: resources/irs_forms/2025/f8995.pdf
# Pages: 1
# Total AcroForm fields: 33

# --- All PDF AcroForm field names (for reference) ---
PDF_FIELDS = [
    "topmostSubform[0].Page1[0].Line2_ReadOrder[0].f1_18[0]",
    "topmostSubform[0].Page1[0].Line6_ReadOrder[0].f1_22[0]",
    "topmostSubform[0].Page1[0].Table[0].Row1i[0].f1_03[0]",
    "topmostSubform[0].Page1[0].Table[0].Row1i[0].f1_04[0]",
    "topmostSubform[0].Page1[0].Table[0].Row1i[0].f1_05[0]",
    "topmostSubform[0].Page1[0].Table[0].Row1ii[0].f1_06[0]",
    "topmostSubform[0].Page1[0].Table[0].Row1ii[0].f1_07[0]",
    "topmostSubform[0].Page1[0].Table[0].Row1ii[0].f1_08[0]",
    "topmostSubform[0].Page1[0].Table[0].Row1iii[0].f1_09[0]",
    "topmostSubform[0].Page1[0].Table[0].Row1iii[0].f1_10[0]",
    "topmostSubform[0].Page1[0].Table[0].Row1iii[0].f1_11[0]",
    "topmostSubform[0].Page1[0].Table[0].Row1iv[0].f1_12[0]",
    "topmostSubform[0].Page1[0].Table[0].Row1iv[0].f1_13[0]",
    "topmostSubform[0].Page1[0].Table[0].Row1iv[0].f1_14[0]",
    "topmostSubform[0].Page1[0].Table[0].Row1v[0].f1_15[0]",
    "topmostSubform[0].Page1[0].Table[0].Row1v[0].f1_16[0]",
    "topmostSubform[0].Page1[0].Table[0].Row1v[0].f1_17[0]",
    "topmostSubform[0].Page1[0].f1_01[0]",
    "topmostSubform[0].Page1[0].f1_02[0]",
    "topmostSubform[0].Page1[0].f1_19[0]",
    "topmostSubform[0].Page1[0].f1_20[0]",
    "topmostSubform[0].Page1[0].f1_21[0]",
    "topmostSubform[0].Page1[0].f1_23[0]",
    "topmostSubform[0].Page1[0].f1_24[0]",
    "topmostSubform[0].Page1[0].f1_25[0]",
    "topmostSubform[0].Page1[0].f1_26[0]",
    "topmostSubform[0].Page1[0].f1_27[0]",
    "topmostSubform[0].Page1[0].f1_28[0]",
    "topmostSubform[0].Page1[0].f1_29[0]",
    "topmostSubform[0].Page1[0].f1_30[0]",
    "topmostSubform[0].Page1[0].f1_31[0]",
    "topmostSubform[0].Page1[0].f1_32[0]",
    "topmostSubform[0].Page1[0].f1_33[0]",
]

# --- Header map (entity identification) ---
HEADER_MAP: FieldMap = {
    # "entity_name": AcroField("..."),
    # "ein": AcroField("..."),
}

# --- Field map (mapping_key -> PDF field) ---
FIELD_MAP: FieldMap = {
    # "LINE_KEY": AcroField("pdf_field_name", format="currency"),
}
