"""Extract AcroForm fields from all PDF templates and generate field map stubs.

Scans resources/irs_forms/2025/ for PDF files, extracts AcroForm field names,
generates stub field map files in apps/tts_forms/field_maps/, and writes an
inventory JSON to specs/pdf_field_inventory.json.
"""
import json
import os

from pypdf import PdfReader

TEMPLATE_DIR = os.path.join(
    os.path.dirname(__file__), "..", "..", "resources", "irs_forms", "2025"
)
FIELDMAP_DIR = os.path.join(
    os.path.dirname(__file__), "..", "apps", "tts_forms", "field_maps"
)
INVENTORY_FILE = os.path.join(
    os.path.dirname(__file__), "..", "specs", "pdf_field_inventory.json"
)

# Skip instruction PDFs and non-form files
SKIP_PREFIXES = ("i",)  # instruction PDFs like i1120s.pdf


def extract_all():
    os.makedirs(FIELDMAP_DIR, exist_ok=True)
    inventory = {}
    total_fields = 0
    stubs_generated = 0

    for filename in sorted(os.listdir(TEMPLATE_DIR)):
        if not filename.endswith(".pdf"):
            continue
        # Skip instruction PDFs
        base = filename.replace(".pdf", "")
        if any(base.startswith(p) for p in SKIP_PREFIXES):
            continue
        # Skip non-standard files (backups, fillable duplicates)
        if ".bak" in filename or "_fillable" in filename:
            continue

        filepath = os.path.join(TEMPLATE_DIR, filename)

        # Derive form_id: strip _2025 suffix if present, else use base name
        form_id = base

        try:
            reader = PdfReader(filepath)
            fields = reader.get_fields() or {}
            page_count = len(reader.pages)

            # Filter to actual field objects (skip structural nodes)
            real_fields = {
                k: v for k, v in fields.items()
                if v.get("/FT") in ("/Tx", "/Btn", "/Ch")
            }

            if not real_fields:
                print(f"  {filename}: {page_count} pages, NO AcroForm fields (flat PDF)")
                inventory[form_id] = {
                    "filename": filename,
                    "pages": page_count,
                    "field_count": 0,
                    "has_acroform": False,
                    "render_method": "coordinate_overlay",
                }
                continue

            field_names = sorted(real_fields.keys())
            text_count = sum(1 for v in real_fields.values() if v.get("/FT") == "/Tx")
            btn_count = sum(1 for v in real_fields.values() if v.get("/FT") == "/Btn")
            print(f"  {filename}: {page_count} pages, {len(field_names)} fields ({text_count} text, {btn_count} checkbox)")

            inventory[form_id] = {
                "filename": filename,
                "pages": page_count,
                "field_count": len(field_names),
                "text_fields": text_count,
                "checkbox_fields": btn_count,
                "has_acroform": True,
                "render_method": "acroform_overlay",
                "fields": field_names,
            }
            total_fields += len(field_names)

            # Generate stub field map if one doesn't exist
            # Map form_id to field_map module name
            map_name = f"{form_id}_2025.py"
            map_file = os.path.join(FIELDMAP_DIR, map_name)
            if not os.path.exists(map_file):
                _write_stub(map_file, form_id, field_names, filename, page_count)
                print(f"    -> Generated stub: {map_name}")
                stubs_generated += 1
            else:
                print(f"    -> Field map exists: {map_name}")

        except Exception as e:
            print(f"  {filename}: ERROR - {e}")
            inventory[form_id] = {"filename": filename, "error": str(e)}

    # Write inventory JSON
    os.makedirs(os.path.dirname(INVENTORY_FILE), exist_ok=True)
    with open(INVENTORY_FILE, "w") as f:
        json.dump(inventory, f, indent=2, sort_keys=True)

    acroform_count = sum(1 for v in inventory.values() if v.get("has_acroform"))
    flat_count = sum(1 for v in inventory.values() if v.get("has_acroform") is False)

    print(f"\n{'='*60}")
    print(f"Templates scanned:        {len(inventory)}")
    print(f"AcroForm templates:       {acroform_count} (can use overlay)")
    print(f"Flat templates:           {flat_count} (need coordinate overlay)")
    print(f"Field map stubs generated: {stubs_generated}")
    print(f"Total PDF fields extracted: {total_fields:,}")
    print(f"Inventory: {INVENTORY_FILE}")
    print(f"{'='*60}")


def _write_stub(path, form_id, field_names, template_filename, page_count):
    """Generate a Python field map stub with all PDF field names listed."""
    lines = [
        '"""',
        f"Field map stub for {template_filename}",
        f"Generated by extract_field_maps.py -- needs mapping.",
        "",
        "Each entry maps a seed line mapping_key to the PDF AcroForm field name.",
        "TODO: Map each field to the corresponding FormLine mapping_key.",
        '"""',
        "",
        "from . import AcroField, FieldMap",
        "",
        f"# PDF template: resources/irs_forms/2025/{template_filename}",
        f"# Pages: {page_count}",
        f"# Total AcroForm fields: {len(field_names)}",
        "",
        "# --- All PDF AcroForm field names (for reference) ---",
        "PDF_FIELDS = [",
    ]
    for name in field_names:
        lines.append(f'    "{name}",')
    lines.append("]")
    lines.append("")
    lines.append("# --- Header map (entity identification) ---")
    lines.append("HEADER_MAP: FieldMap = {")
    lines.append('    # "entity_name": AcroField("..."),')
    lines.append('    # "ein": AcroField("..."),')
    lines.append("}")
    lines.append("")
    lines.append("# --- Field map (mapping_key -> PDF field) ---")
    lines.append("FIELD_MAP: FieldMap = {")
    lines.append('    # "LINE_KEY": AcroField("pdf_field_name", format="currency"),')
    lines.append("}")
    lines.append("")

    with open(path, "w") as f:
        f.write("\n".join(lines))


if __name__ == "__main__":
    extract_all()
