# Generated by Django 5.2.11 on 2026-02-21 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_help", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="helpquery",
            name="mode",
            field=models.CharField(
                choices=[("grounded", "IRS-Grounded"), ("broad", "Broader Search")],
                default="grounded",
                max_length=10,
            ),
        ),
    ]
