# Generated by Django 5.2.11 on 2026-03-22 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diagnostics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="diagnosticrule",
            name="category",
            field=models.CharField(
                choices=[("preparer", "Preparer"), ("internal", "Internal")],
                default="preparer",
                max_length=20,
            ),
        ),
    ]
